{{- if .Values.docs.rancher.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: rancher-offline-docs
spec:
  label: Rancher Docs
  description: Rancher Multi-cluster Manager
  group: Offline Docs
  sideLabel: Multi-cloud
  target: _blank
  iconSrc: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE5LjIuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA1MDAuMiAyNTQiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDUwMC4yIDI1NDsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiMyNDUzRkY7fQoJLnN0MXtmaWxsOiMwMDAwMDA7fQoJLnN0MntmaWxsOiNDQ0NDQ0M7fQoJLnN0M3tmaWxsOiNCM0IzQjM7fQoJLnN0NHtmaWxsOiNGRkZGRkY7fQo8L3N0eWxlPgo8cGF0aCBjbGFzcz0ic3QxIiBkPSJNMS42LDE2OS41aDM0LjJjMTYuMiwwLDI3LjIsNy45LDI3LjIsMjMuMWMwLDEyLjQtOC41LDE5LjktMTYuNywyMi41YzIuNSwyLjEsNC4zLDQuOSw1LjgsNy45CgljMy40LDcsNS44LDE0LjgsMTMsMTQuOGMxLjgsMCwzLjMtMC42LDMuMy0wLjZsLTEuNiwxNC42YzAsMC00LjQsMS4xLTguMiwxLjFjLTkuOCwwLTE1LjUtMy44LTIxLjMtMTdjLTIuNS01LjktNS45LTE2LjItMTAuNS0xNi4yCgloLTQuN3YzMi44SDEuNlYxNjkuNXogTTIyLjEsMTg0LjR2MjAuNGg3LjRjNS45LDAsMTIuOC0xLjgsMTIuOC0xMC43YzAtNy4zLTQuNy05LjctMTAuMy05LjdIMjIuMXogTTkwLjgsMTY5LjVoMjAuOGwyOCw4M2gtMjAuOAoJbC01LjItMTUuN0g4NS45bC01LDE1LjdoLTE4TDkwLjgsMTY5LjV6IE05MC44LDIyMS41aDE3LjhsLTUuNy0xNy41Yy0yLTUuOS0yLjgtMTQuMy0yLjgtMTQuM2gtMC41YzAsMC0xLjIsOC41LTMuMSwxNC4xCglMOTAuOCwyMjEuNXogTTE0MC41LDI1Mi41aDE2Ljl2LTM5LjljMC00LjUtMC42LTEwLjEtMS0xNC44aDAuNWMxLjcsNC40LDMuOSw5LjgsNiwxMy41bDIyLjYsNDEuMUgyMDd2LTgzaC0xNi45djM5LjkKCWMwLDQuOCwwLjYsMTEuNCwwLjksMTYuMWgtMC41Yy0yLTQuOS00LjQtMTEuMi02LjMtMTQuOGwtMjEuOC00MS4yaC0yMlYyNTIuNXogTTIxMS40LDIxMC40YzAsMzAuMywxNC41LDQzLjUsMzcsNDMuNQoJYzIyLjEsMCwzNC4zLTEyLjQsMzMtMjkuM2wtMTgtMS44YzEuNSwxMC44LTUuNCwxNi4xLTEzLjksMTYuMWMtOSwwLTE2LjktNS44LTE2LjktMjguNGMwLTIxLjQsNy4zLTI4LDE2LjItMjgKCWM5LjMsMCwxNC41LDUuMywxMi40LDE4LjVsMTkuMi0xLjdjMi43LTE4LTctMzEuMi0zMS4yLTMxLjJDMjI2LjMsMTY4LDIxMS40LDE4MC40LDIxMS40LDIxMC40IE0yODUuNiwyNTIuNWgyMC41di0zNS4yaDI1LjJ2MzUuMgoJaDIwLjV2LTgzaC0yMC41djMxLjRoLTI1LjJ2LTMxLjRoLTIwLjVWMjUyLjV6IE0zNjAuMSwyNTIuNWg1Ni4ydi0xNS4zaC0zNS43di0xOS40aDI4Ljl2LTE1LjNoLTI4Ljl2LTE3LjhoMzQuNHYtMTUuM2gtNTVWMjUyLjV6CgkgTTQyMC4zLDE2OS41aDM0LjJjMTYuMiwwLDI3LjIsNy45LDI3LjIsMjMuMWMwLDEyLjQtOC41LDE5LjktMTYuNywyMi41YzIuNSwyLjEsNC4zLDQuOSw1LjgsNy45YzMuNCw3LDUuOCwxNC44LDEzLDE0LjgKCWMxLjgsMCwzLjMtMC42LDMuMy0wLjZsLTEuNiwxNC42YzAsMC00LjQsMS4xLTguMiwxLjFjLTkuOCwwLTE1LjUtMy44LTIxLjMtMTdjLTIuNS01LjktNS45LTE2LjItMTAuNS0xNi4yaC00Ljd2MzIuOGgtMjAuNVYxNjkuNXoKCSBNNDQwLjgsMTg0LjR2MjAuNGg3LjRjNS45LDAsMTIuOC0xLjgsMTIuOC0xMC43YzAtNy4zLTQuNy05LjctMTAuMy05LjdINDQwLjh6Ii8+CjxnPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTM5My4yLDMwLjdMMzkwLDExLjNjLTEtNi4yLTMuNS0xMS4zLTUuNC0xMS4zYy0xLjksMC0zLjUsNS4yLTMuNSwxMS41djUuMWMwLDYuMy01LjIsMTEuNS0xMS41LDExLjVoLTUuMQoJCWMtMC40LDAtMC43LDAtMS4xLDBWNDJjMC40LDAsMC43LDAsMS4xLDBoMTkuMUMzODkuOSw0MiwzOTQuMiwzNi45LDM5My4yLDMwLjciLz4KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0zNDcuNSwxNC4zaC0zMC45Yy0wLjMsMC0wLjUsMC0wLjgsMEgyODRjLTAuNCwwLTAuNywwLTEuMSwwLjF2LTNjMC02LjMtMS42LTExLjUtMy41LTExLjVzLTQuNCw1LjEtNS40LDExLjMKCQlsLTMuMiwxOS40Yy0xLDYuMiwzLjMsMTEuMyw5LjYsMTEuM2gxOS4xYzIsMCwzLjgtMC4zLDUuNC0wLjhjLTAuNiwzLjMtMy41LDUuNy02LjksNS43aC0yNi44Yy00LjMsMC03LjYtMy45LTYuOS04LjJsMi43LTE2LjMKCQljMC43LTQuMy0yLjYtOC4yLTYuOS04LjJIMTI3Yy0yLjgsMC01LjMsMS43LTYuNCw0LjFMOTUuNiw1Ni42Yy0wLjQsMC42LTAuNCwxLjUsMC4xLDIuMWw0LjksNS43YzAuNiwwLjcsMS43LDAuOCwyLjQsMC4ybDE3LTEzLjQKCQl2ODEuNmMwLDMuOSwzLjEsNyw3LDdoMzcuOGMzLjksMCw3LTMuMSw3LTd2LTI4LjRjMC0zLjksMy4xLTcsNy03aDk0LjRjMy45LDAsNywzLjEsNyw3djI4LjRjMCwzLjksMy4xLDcsNyw3SDMyNWMzLjksMCw3LTMuMSw3LTcKCQl2LTMwLjVoLTIwLjFjLTYuMywwLTExLjUtNS4yLTExLjUtMTEuNVY3MS4yYzAtMy43LDEuOC03LjEsNC42LTkuMnYyMy40YzAsNi4zLDUuMiwxMS41LDExLjUsMTEuNWgzMC45YzYuMywwLDExLjUtNS4yLDExLjUtMTEuNQoJCVYyNS44QzM1OC45LDE5LjUsMzUzLjgsMTQuMywzNDcuNSwxNC4zIi8+CjwvZz4KPHBhdGggY2xhc3M9InN0MSIgZD0iTTQ4Ny40LDE3My42YzAtMy45LDIuOS01LjYsNS42LTUuNnM1LjYsMS43LDUuNiw1LjZjMCwzLjgtMi45LDUuNS01LjYsNS41UzQ4Ny40LDE3Ny40LDQ4Ny40LDE3My42egoJIE00OTcuMywxNzMuNmMwLTMuMS0yLTQuNC00LjItNC40Yy0yLjIsMC00LjMsMS4zLTQuMyw0LjRjMCwzLDIuMSw0LjQsNC4zLDQuNEM0OTUuMywxNzgsNDk3LjMsMTc2LjYsNDk3LjMsMTczLjZ6IE00OTEuMiwxNzAuOGgyCgljMSwwLDIsMC4zLDIsMS43YzAsMC44LTAuNiwxLjMtMS4zLDEuNWwxLjMsMi4zSDQ5NGwtMS4yLTIuMmgtMC41djIuMmgtMS4xVjE3MC44eiBNNDkzLjIsMTczLjNjMC41LDAsMC45LTAuMywwLjktMC44CgljMC0wLjYtMC41LTAuNy0wLjktMC43aC0xdjEuNUg0OTMuMnoiLz4KPC9zdmc+Cg==
  toService:
    name: rancher-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.rke2.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: rke2-offline-docs
spec:
  label: RKE2 Docs
  description: Secure-by-default Kubernetes
  group: Offline Docs
  sideLabel: Distro
  target: _blank
  iconSrc: data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMTY1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6IzExNjdmMTt9LmNscy0ye2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHJlY3QgY2xhc3M9ImNscy0xIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE2NSIgcng9IjIwIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNMTA0Ljk1NTA4LDg2Ljc4NjYyYTEwLjAwMzI5LDEwLjAwMzI5LDAsMCwxLTkuNzEwOTQtNy42NDk5TDg2LjM5OCw0Mi41ODk4NEgzOS40NTU1N2ExMCwxMCwwLDEsMSwwLTIwSDk0LjI2NjExYTkuOTk5NDgsOS45OTk0OCwwLDAsMSw5LjcxOTI0LDcuNjQ3NDZsMTAuNjk3MjcsNDQuMTk0MzRhMTAuMDA5NTMsMTAuMDA5NTMsMCwwLDEtOS43Mjc1NCwxMi4zNTVaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNTMuMDI1MzksNjguMTUwODhhOS45OTk4Nyw5Ljk5OTg3LDAsMCwxLTEwLTEwdi0yNS41NjFhMTAsMTAsMCwxLDEsMjAsMHYyNS41NjFBOS45OTk4Nyw5Ljk5OTg3LDAsMCwxLDUzLjAyNTM5LDY4LjE1MDg4WiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTEzMC4yMTI0LDEyNC44MDE3Nkg5OC45NTQ1OWExMC4wMDAxOSwxMC4wMDAxOSwwLDAsMS0xMC05Ljk4ODI4bC0uMDA2ODQtNS44Njg2NmEzMy4wOSwzMy4wOSwwLDAsMC0zMy4wNTAyOS0zMy4wNjJIMzkuNDU1NTdhMTAsMTAsMCwxLDEsMC0yMEg1NS44OTc0NmE1My4xMjM4OSw1My4xMjM4OSwwLDAsMSw1Mi44OTExMSw0OC45MTlIMTMwLjIxMjRhMTAsMTAsMCwwLDEsMCwyMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNTQuMTU4NjksMTA4LjkzMzExYTkuOTk5ODgsOS45OTk4OCwwLDAsMS0xMC0xMFY4Ni43ODQxOEgxMDQuOTYzMzhhMTAsMTAsMCwwLDEsMC0yMGg0NS42MDQ0OUExMy42MDYsMTMuNjA2LDAsMCwxLDE2NC4xNTg2OSw4MC4zNzVWOTguOTMzMTFBOS45OTk4OCw5Ljk5OTg4LDAsMCwxLDE1NC4xNTg2OSwxMDguOTMzMTFaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNTIuNzQwNiwxMDIuMDkwMDlhMTAsMTAsMCwxLDEtMTAsMTAsOS45OTk5NSw5Ljk5OTk1LDAsMCwxLDEwLTEwbTAtMjBhMzAsMzAsMCwxLDAsMzAsMzAsMzAuMDM0LDMwLjAzNCwwLDAsMC0zMC0zMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNTEuOTI2NTcsMTEyLjA5MDA5YTUsNSwwLDEsMS01LDUsNSw1LDAsMCwxLDUtNW0wLTIwYTI1LDI1LDAsMSwwLDI1LDI1LDI1LjAyODMzLDI1LjAyODMzLDAsMCwwLTI1LTI1WiIvPjwvc3ZnPg==
  toService:
    name: rke2-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.k3s.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: k3s-offline-docs
spec:
  label: k3s Docs
  description: Lightweight Kubernetes
  group: Offline Docs
  sideLabel: Distro
  target: _blank
  iconSrc: data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTQuMjU2MTkgMTU5LjA4OTEyIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2ZmYzYxYzt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnN1Yi1wcm9qZWN0LWJyYW5kLWxvZ28tdmFyaWFudHM8L3RpdGxlPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTE3My42OTU0OCwwSDIwLjU2MDcxQTIwLjYyMTI0LDIwLjYyMTI0LDAsMCwwLS4wMDAwOCwyMC41NjA2OFYxMzguNTI4NDVhMjAuNjIxMjQsMjAuNjIxMjQsMCwwLDAsMjAuNTYwNzksMjAuNTYwNjdIMTczLjY5NTQ4YTIwLjYyMTI0LDIwLjYyMTI0LDAsMCwwLDIwLjU2MDc5LTIwLjU2MDY3VjIwLjU2MDY4QTIwLjYyMTI0LDIwLjYyMTI0LDAsMCwwLDE3My42OTU0OCwwWk04Mi4wODI5MywxMTUuNjg2NjYsNDQuNzEwODYsMTM3LjQwNDkyYTkuOTk5OSw5Ljk5OTksMCwxLDEtMTAuMDQ4ODMtMTcuMjkyTDcyLjAzNDEsOTguMzk0NjZhOS45OTk5LDkuOTk5OSwwLDEsMSwxMC4wNDg4MywxNy4yOTJaTTk2Ljc4NTA4LDgyLjU5Nzc5aC0uMDQ0OTJBOS45OTk1Niw5Ljk5OTU2LDAsMCwxLDg2Ljc4NDE3LDcyLjU1NDMzbC4xODc1LTQzLjA1MzIyYTEwLjAwMDgxLDEwLjAwMDgxLDAsMCwxLDkuOTk5LTkuOTU2NTRoLjA0NDkzYTkuOTk5ODQsOS45OTk4NCwwLDAsMSw5Ljk1NiwxMC4wNDM0NWwtLjE4NzUsNDMuMDUzMjNBMTAuMDAwOCwxMC4wMDA4LDAsMCwxLDk2Ljc4NTA4LDgyLjU5Nzc5Wm02Ni4xMjUsNTEuMTU3MjNhOS45OTU2Nyw5Ljk5NTY3LDAsMCwxLTEzLjY2MDE2LDMuNjYwMTVsLTM3LjQyNjc2LTIxLjYwODRhOS45OTk5MSw5Ljk5OTkxLDAsMCwxLDEwLTE3LjMyMDMxbDM3LjQyNjc2LDIxLjYwODRBOS45OTkzNyw5Ljk5OTM3LDAsMCwxLDE2Mi45MTAwOCwxMzMuNzU1WiIvPjwvc3ZnPg==
  toService:
    name: k3s-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.longhorn.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: longhorn-offline-docs
spec:
  label: Longhorn Docs
  description: Cloud-native block storage
  group: Offline Docs
  sideLabel: Storage
  target: _blank
  iconSrc: data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTQuMjU2MTkgMTU5LjA4OTEyIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6IzVmMjI0YTt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnN1Yi1wcm9qZWN0LWJyYW5kLWxvZ28tdmFyaWFudHM8L3RpdGxlPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTk3LjEyODEsODAuNjI2OWExMC4wMDksMTAuMDA5LDAsMCwxLTEuOTU4LS4xOTMzNmwtNS4yODM5NC0xLjA1NDkzLDQuNTQ4NTksMjcuOTgzMTVhOS45MjQyOSw5LjkyNDI5LDAsMCwxLC4xMjk4OCwxLjYwNDQ5aDUuMTI2YTkuOTk5Nyw5Ljk5OTcsMCwwLDEsLjE2MzA4LTEuNzk3MzZsNS4wOTgxNS0yNy45MDY0M0w5OS4wODYxLDgwLjQzMzU0QTEwLjAwODkyLDEwLjAwODkyLDAsMCwxLDk3LjEyODEsODAuNjI2OVoiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xNzMuNjk1NiwwSDIwLjU2MDcxQTIwLjYyMTA1LDIwLjYyMTA1LDAsMCwwLDAsMjAuNTYwNjdWMTM4LjUyODQ1YTIwLjYyMTA2LDIwLjYyMTA2LDAsMCwwLDIwLjU2MDY3LDIwLjU2MDY3SDE3My42OTU2YTIwLjYyMSwyMC42MjEsMCwwLDAsMjAuNTYwNTUtMjAuNTYwNjdWMjAuNTYwNjdBMjAuNjIxLDIwLjYyMSwwLDAsMCwxNzMuNjk1NiwwWm0zLjQ1NSw0MS41ODEtMi41MDIsMTdhMTAuMDAwNiwxMC4wMDA2LDAsMCwxLTcuOTM1NTQsOC4zNTA1OEwxMjYuMDQ1NDUsNzUuMDUxYy0uMDA3LjA0MDcxLS4wMDg1NC4wODEwNi0uMDE2LjEyMTc3bC02LjM2NjIxLDM0Ljg1MDU4QTIwLjAyNjUsMjAuMDI2NSwwLDAsMSw5OS42OTA2LDEyOC45NjYyNWgtNS4xMjZhMjAuMDI1ODcsMjAuMDI1ODcsMCwwLDEtMTkuOTc4NTItMTkuMDU4MUw2OC45NDQ3NSw3NS4xOTc1OGwtNDEuNDAxNjItOC4yNjZBMTAuMDAwNiwxMC4wMDA2LDAsMCwxLDE5LjYwNzU5LDU4LjU4MWwtMi41MDItMTdhMTAuMDAwMTMsMTAuMDAwMTMsMCwwLDEsMTkuNzg3MTEtMi45MTIxMWwxLjQ3NTU5LDEwLjAyOTNMOTcuMTI4MSw2MC40Mjk2M2w1OC43NTk3Ni0xMS43MzE0NCwxLjQ3NTU5LTEwLjAyOTNBMTAuMDAwMTMsMTAuMDAwMTMsMCwwLDEsMTc3LjE1MDU2LDQxLjU4MVoiLz48L3N2Zz4=
  toService:
    name: longhorn-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.fleet.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: fleet-offline-docs
spec:
  label: Fleet Docs
  description: Continuous delivery for Kubernetes
  group: Offline Docs
  sideLabel: GitOps
  target: _blank
  iconSrc: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPgAAADMCAMAAABp5J6CAAAAe1BMVEUirV////8Nqleh2LYYq1sAqVQnr2K33sX5/PoAp09owYrk9Orw+fQWq1oAqFTL6dau3L90xpSEzKDc8OTB4sz1/Pim2brU7d5KuHc0smpZvYHh8uiX065Sunxgv4YxsmmJzqS944zQ69pwxJGIzaJ+ypyR0aoAo0M/tXGK+ZiZAAANrklEQVR4nO2di3aiOhSGIYISFbRaa0drq239+P5PeGQH7N4kQBBJUuy/zjqzFtOpfOayrwTPV2m1nB3mgx5ofpgtV0pET7oSHY4fPEwS1gslScg/joeoFnz9FSex1zNdkL7WleDLXdg7aqE43C1LwaMjD2zfYHcK+DFSg6+HzPbNdSs2XKvAB30ebqGAD2TwPbd9WybE90XwRWj7nswoPFLwtwfhvpC/YfDDQ8xzIX74AZ8+zHinCqdX8Nfe7+dYwWsOPnJiwIOhqU8KRxm4qQ+sVLAbmfOfBPjciQGPo1Fi6rPCOYD/c2GF87VvDjz4l4J/ujDg/DIG5sC98PMC/uRAIJqk/pRB8Ph4AXeAO975ZsG9wPeWDjhtwco0OF96c/tBOBdhsklwNvdO1qZ6EJ/hzzALkk2CxydvbMuYhZsZ/MnGvnnwYOydzX0aFvNGIkQIPiIL4BfsD4OfdhUk/r5hd+HX5KdRcCvYXnhe5jmA1Hu0AW4sIkJiLIWdwnizL98OuHkF/Ams9pku8N6Dh2dhtL+BMsSFnT6Dx/xFQM7EAh/4jwHO36eCMQLnId74DwHOhs854xjcRbZ6BPCA768b2RwmOp/5DwAOpjvTBFIfbOH3Hzwm29g5nehp+qf34Czf1EAnYcmW/QeP3zGfyHzkJaxegzM83pnL9ipx9w88fMF4YqLzaf/BYzK4y2JM1l9wvsV0H+lEL7hs/QRnewy3h2A0nDwA+FAx0V9U3D0Dp36p2NF3Su5+gbMnjCY6bVQ7egHcgepOSwU4ABM+Op3oMyX40X6V40YxkcWkZmsnuy6TjQqc+btfOub87QsgzxhSNCBw4qO/jlXgYRR5LhTtmyqOP5cCEqfUViIYPWHuF14C7i9dqNo3VLhZie07/sKQkHUJPvClaRiXgfuHX0fO3/JZHeLte6bIuuyCoBTcP/0u8phd0CLYmhKSQ/0nz4HL11MB/rs2uOQ1tV+L1BrRWf0msg/YuqX9lFXg0S/a3zjk0SbyrJ4qTPh7XA3uu9CsoaUAWgZ9fwOz+r0IWbBusHtVgl82fWssTRQPhYnOtjEcgWWXsHWLoF5ZDe4//QYPLtxktwumjB0RpA+Q1G+HfaAOXITvbovnnokwwAnexgaAxPBDQNn6rQOfuG7TAnYtD4GXTkyZKIVTv/0shrIOPCu6OKt4eF3RLzBGQzy6EGvRAsJLBlkL7n+5vMyT3c+dyqO7FX47sW45TT14NHR3mYeoCnaC0SV2C6JR7JRfhjF3yurB/bWzyxwPb+ao4NF9Fnk2bN0+rwtXA9zZJ6TIHIYsakySasKUkVzr+Tp7dcDFlHFOZA5P5VyD2OwCjIIeidACd/MhKUIJXgn5KkSkkeDNLkIcWuBOPhanGnC8nGGz80igtkAGSg/cdzD5SMrcx3SzJjF35rs8o0tbPHE1wSMnnpvBCnAMJsLRENfKRGROEqvvOL+gCe5eCo5/ort7kgZ8IkdlM4KgC55Vl50RqQZNZYMNCUbqu9B4SxvcjYfEriKeiphOOPbcynO/8HSfPvjWpZ2dBB5T0eqAB/wdnFUShhfGTR/cKQcuSzUJQd89oRQxN6kRvhXsUgNw5O9ZF659T+VKKOzfMU7FrIpbVBPwrTNDnuCk6OUWF7+r7WWYPPjWpZ2dBB5T0eqAB/wdnFUShhfGTR/cKQcuSzUJQd89oRQxN6kRvhXsUgNw5O9ZF659T+VKKOzfMU7FrIpbVBPwrTNDnuCk6OUWF7+r7WWYPPjWpZ2dBB5T0eqAB/wdnFUShhfGTR/cKQcuSzUJQd89oRQxN6kRvhXsUgNw5O9ZF659T+VKKOzfMU7FrIpbVBPwrTNDnuCk6OUWF7+r7WWYPPjWpZ2dBB5T0eqAB/wdnFUShhfGTR/cKQcuSzUJQd89oRQxN6kRvhXsUgNw5O9ZF659T+VKKOzfMU7FrIpbVBPwrTNDnuCk6OUWF7+r7WWYPPjWpZ2dBB5T0eqAB/wdnFUShhfGTR/cKQcuSzUJQd89oRQxN6kRvhXsUgNw5O9ZF659T+VKKOzfMU7FrIpbVBPwrTNDnuCk6OUWF7+r7WWYPPg==
  toService:
    name: fleet-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.kubewarden.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: kubewarden-offline-docs
spec:
  label: Kubewarden Docs
  description: Policy engine for Kubernetes
  group: Offline Docs
  sideLabel: Security
  target: _blank
  iconSrc: data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMTY1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2JjMmE0Njt9LmNscy0ye2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHJlY3QgY2xhc3M9ImNscy0xIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE2NSIgcng9IjIwLjI5MzUzIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNMTAwLDY4LjYyMzU0bDExLjQxNDE5LDUuNDk2ODIsMi44MTkwOSwxMi4zNTEwOC03Ljg5ODkzLDkuOTA1SDkzLjY2NTYybC03Ljg5ODgtOS45MDUsMi44MTkwOS0xMi4zNTEwOEwxMDAsNjguNjIzNTRtMC04LjQ3OUw5Ni42ODU0LDYxLjc0MDcyLDg1LjI3MTMzLDY3LjIzNzU1bC0zLjMxNDU3LDEuNTk2MTktLjgxODYsMy41ODY2Ny0yLjgxOTEsMTIuMzUxMDctLjgxODYsMy41ODY2NywyLjI5MzcsMi44NzYyMyw3Ljg5ODgsOS45MDUsMi4yOTM3MSwyLjg3NjIyaDIwLjAyNjQ5bDIuMjkzODItMi44NzYyMiw3Ljg5ODkyLTkuOTA1LDIuMjkzNzEtMi44NzYyMy0uODE4NjEtMy41ODY2Ny0yLjgxOTA5LTEyLjM1MTA3LS44MTg2LTMuNTg2NjctMy4zMTQ1OC0xLjU5NjE5LTExLjQxNDE4LTUuNDk2ODNMMTAwLDYwLjE0NDUzWiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTEwMC4wMDAwOSwzOS45MjA5bDMxLjU2MTE2LDE1LjMxOTgydjM4LjI3NzFjMCwxNy40MzA2Ny0zMS41NjExNiwzMS41NjEyOC0zMS41NjExNiwzMS41NjEyOHMtMzEuNTYxNC0xNC4xMzA2MS0zMS41NjE0LTMxLjU2MTI4VjU1LjI0MDcybDMxLjU2MTQtMTUuMzE5ODJtMC0xNi42NzM1OS02LjU1MDE3LDMuMTc5Mkw2MS44ODg1Miw0MS43NDYzNCw1My40Mzg2OSw0NS44NDc5VjkzLjUxNzgyYzAsMTIuMzExMjgsNy4zOTY4NSwyMy45MDgsMjEuOTg1MjMsMzQuNDY3NzhhMTEzLjYyOTg1LDExMy42Mjk4NSwwLDAsMCwxOC40NDY2NiwxMC43ODM5M2w2LjEyOTUxLDIuNzQ0MzksNi4xMjk1Mi0yLjc0NDM5YTExMy42MzEzOSwxMTMuNjMxMzksMCwwLDAsMTguNDQ2NTMtMTAuNzgzOTNjMTQuNTg4MjYtMTAuNTU5ODIsMjEuOTg1MTEtMjIuMTU2NSwyMS45ODUxMS0zNC40Njc3OFY0NS44NDc5bC04LjQ0OTgzLTQuMTAxNTZMMTA2LjU1MDI2LDI2LjQyNjUxbC02LjU1MDE3LTMuMTc5MloiLz48L3N2Zz4=
  toService:
    name: kubewarden-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.harvester.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: harvester-offline-docs
spec:
  label: Harvester Docs
  description: Hyper-converged infrastructure
  group: Offline Docs
  sideLabel: HCI
  target: _blank
  toService:
    name: harvester-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}

{{- if .Values.docs.rancherdesktop.enabled }}
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: rd-offline-docs
spec:
  label: Rancher Desktop Docs
  description: Developer container runtime
  group: Offline Docs
  sideLabel: Dev Env
  target: _blank
  toService:
    name: rd-offline-docs
    namespace: {{ .Values.namespace }}
    port: "80"
    scheme: http
{{- end }}
