name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        find . -name Dockerfile | while read -r dockerfile; do
          dir=$(dirname "$dockerfile")
          image=$(basename "$dir")

          echo "Building $image from $dockerfile"
          docker build "$dir" --file "$dockerfile" --tag "$image:$(date +%s)"
          echo ""
        done