name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: for i in $(find . -name Dockerfile | cut -d'/' -f2 | tr '\n' ' '); do echo Building $1; docker build ./$i --file Dockerfile --tag $i:$(date +%s); echo ""; done
